base: 'http://cswproject.s2310456025.student.kwmhgb.at/'
languages:
  -
    title: Deutsch
    enabled: true
    languageId: 0
    base: /
    locale: de_DE
    navigationTitle: Deutsch
    flag: at
    hreflang: de_DE
    websiteTitle: ''
  -
    title: English
    enabled: true
    locale: en_US
    hreflang: en-US
    base: /en/
    websiteTitle: 'One Piece'
    navigationTitle: ''
    fallbackType: strict
    fallbacks: ''
    flag: en-us-gb
    languageId: 1
rootPageId: 1
websiteTitle: Project
